heat_template_version: 2014-10-16

description: a template to deploy a simple compute instance (trusty distro) to run Sonata Service Platform for the Qualification environment

parameters:
  key_name:
    type: string
    label: Key Name
    description: name of key-pair to be used for compute instance
    default: son-ift-ptin
  image_id:
    type: string
    label: Image ID
    description: image to be used for the compute instance
    default: trusty-cldimg
  instance_type:
    type: string
    label: Instance Type
    description: type of instance (flavor) to be used
    default: m1.small
    constraints:
      - allowed_values: [ m1.micro, m1.tiny, m1.small, m1.large, m1.xlarge ]
        description: default flavor should be m1.small

resources:
  my_web_instance:
    type: OS::Nova::Server
    properties:
      networks:
        - network: son-qual-netw
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }

  my_db_instance:
    type: OS::Nova::Server
    properties:
      networks:
        - network: son-qual-netw
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
#      user_data_format: RAW
#      user_data:
#        str_replace:
#          template: |
#            #cloud-config
#            write_files:
#              - content: |
#                  #!/bin/bash
#                  voldata_id="%voldata_id%"
#                  voldata_dev="/dev/disk/by-uuid/virtio-$(echo ${voldata_id} | cut -c -20)"
#                  mkfs.ext4 ${voldata_dev}
#                  mkdir -pv /opt/apps
#                  echo "${voldata_dev} /opt/apps ext4 defaults 1 2" >> /etc/fstab
#                  mount /opt/apps
#                path: /tmp/format-disks
#                permissions: '0700'
#            runcmd:
#              - /tmp/format-disks
#          params:
#            "%voldata_id%": { get_resource: db_volume2 } 

#  db_volume2:
#    type: OS::Cinder::Volume
#    properties: 
#      size: 6

#  db_vol_attach:
#    type: OS::Cinder::VolumeAttachment
#    properties: 
#      instance_uuid: { get_resource: my_db_instance }
#      volume_id: { get_resource: db_volume2 } 
#      mountpoint: /dev/vdb

outputs:
  www_instance_ip:
    description: the IP address of the instance
    value: { get_attr: [my_web_instance, first_address] }
  db_instance_ip:
    description: the IP address of the instance
    value: { get_attr: [my_db_instance, first_address] }
